---
  method_name: "batch_inference"
  client_name: "openai"
  transform: "batch_inference.aqua.transform_batch_inference_aqua.BatchInferenceAQuATransform"
  extract: "batch_inference.aqua.extract_batch_inference_aqua.BatchInferenceAQuAExtract"
  extraction_regex: ".*The answer is (.*).\n?"
  prompt_file_path: "batch_inference/aqua/prompt.txt"
  max_tokens: 512
