---
 dataset:
   dataset_name: "commonsense_qa"
   cache_dir: "./data"
 method:
   backend: "openai"
   transform: "cot"
   extract: "regex"
   prompt_file_path: "methods/CoT/prompt_files/commonsense_qa.txt"
   max_tokens: 256
   n: 2
   top_k_return: 2
   temperature: 0.4
