---
  method_name: "binder"
  client_name: "openai"
  prompt_file_path: "binder/tab_fact/prompt.txt"
  transform: "binder"

  # Program Generation
  generation:
    - n_shots: 14
    - generate_type: 'nsql'
    - seed: 42
    - engine: "code-davinci-002"
    - n_parallel_prompts: 2
    - max_generation_tokens: 512
    - max_api_total_tokens: 8001
    - temperature: 0.4
    - sampling_n: 20
    - stop_token: "\n\n"

  # Program Execution
  execution:
    - temperature: 0
    - qa_retrieve_pool_file: "binder/tab_fact/qa_retrieve_pool.json"
    # Aggregation options
    - aggregation: "majority_vote_plus"
    - allow_none_and_empty_answer: true
    - allow_multiple_answers: true
    - answer_placeholder: 0
    # choices=['simple', 'prob', 'answer_biased']
    - answer_biased: 1
    - answer_biased_weight: 4
    - process_program_with_fuzzy_match_on_db: true