---
  dataset:
    dataset_name: "add_sub"
    dataset_split: "validation"
    dataset_subset_name: null
    dataset_key_map:
      question: "sQuestion"
      answer: "lSolutions"
      id: "id"
  method:
    method_name: "batch_inference"
    method_config_file_path: null
    method_args:
      client_name: "openai"
      transform: "batch_inference.add_sub.transform_batch_inference_add_sub.BatchInferenceAddSubTransform"
      extract: "batch_inference.add_sub.extract_batch_inference_add_sub.BatchInferenceAddSubExtract"
      extraction_regex: ".*The answer is (.*).\n?"
      prompt_file_path: "batch_inference/add_sub/prompt-batch=3.txt"
      max_tokens: 512
      temperature: 0
      engine: code-davinci-002
      stop_sequence: "\n\n"
  metrics:
    - "exact_match"
