---
  dataset:
    dataset_name: "strategy_qa"
    dataset_split: "train"
    dataset_subset_name: null
    dataset_key_map:
      question: "question"
      answer: "answer"
      id: "id"
  method:
    method_name: "batch_inference"
    method_config_file_path: null
    method_args:
      client_name: "openai"
      transform: "batch_inference.strategy_qa.transform_batch_inference_strategy_qa.BatchInferenceStrategyQATransform"
      extract: "batch_inference.strategy_qa.extract_batch_inference_strategy_qa.BatchInferenceStrategyQAExtract"
      extraction_regex: ".*So the answer is (.*).\n?"
      prompt_file_path: "batch_inference/strategy_qa/prompt-batch=3.txt"
      max_tokens: 512
      temperature: 0
      engine: code-davinci-002
      stop_sequence: "\n\n"
  metrics:
    - "exact_match"
