---
  dataset:
    dataset_name: "commonsense_qa"
    dataset_split: "validation"
    dataset_subset_name: null
    dataset_key_map:
      question: "question"
      choices: "choices"
      answer: "answerKey"
      id: "id"
  method:
    method_name: "batch_inference"
    method_config_file_path: null
    method_args:
      client_name: "openai"
      transform: "batch_inference.commonsense_qa.transform_batch_inference_commonsense_qa.BatchInferenceCommonsenseQATransform"
      extract: "batch_inference.commonsense_qa.extract_batch_inference_commonsense_qa.BatchInferenceCommonsenseQAExtract"
      extraction_regex: ".*So the answer is (.*).\n?"
      prompt_file_path: "batch_inference/commonsense_qa/prompt-batch=3.txt"
      max_tokens: 512
      temperature: 0
      engine: code-davinci-002
      stop_sequence: "\n\n"
  metrics:
    - "exact_match"
