---
  dataset:
    dataset_name: "aqua"
    dataset_split: "validation"
    dataset_subset_name: null
    dataset_key_map:
      question: "question"
      choices: "choices"
      answer: "answer"
      id: "id"
  method:
    method_name: "batch_inference"
    method_config_file_path: null
    method_args:
      client_name: "openai"
      transform: "batch_inference.aqua.transform_batch_inference_aqua.BatchInferenceAQuATransform"
      extract: "batch_inference.aqua.extract_batch_inference_aqua.BatchInferenceAQuAExtract"
      extraction_regex: ".*So the answer is (.*).\n?"
      prompt_file_path: "batch_inference/aqua/prompt-batch=6.txt"
      max_tokens: 512
      temperature: 0
      engine: code-davinci-002
      stop_sequence: "\n\n"
  metrics:
    - "exact_match"
