---
  dataset:
    dataset_name: "gsm8k"
    dataset_split: "test"
    dataset_subset_name: "main"
    dataset_key_map:
      question: "question"
      answer: "answer"
  method:
    method_name: "batch_inference"
    method_config_file_path: null
    method_args:
      client_name: "openai"
      transform: "batch_inference.gsm8k.transform_batch_inference_gsm8k.BatchInferenceGSM8KTransform"
      extract: "batch_inference.gsm8k.extract_batch_inference_gsm8k.BatchInferenceGSM8KExtract"
      extraction_regex: ".*The answer is (.*).\n?"
      prompt_file_path: "batch_inference/gsm8k/prompt-batch=6.txt"
      max_tokens: 512
      temperature: 0
      engine: code-davinci-002
      stop_sequence: "\n\n"
  metrics:
    - "exact_match"
