---
  dataset: "svamp"
  dataset_split: "validation"
  method:
    method_name: "cot"
    method_args:
      client_name: "openai"
      transform: "cot"
      extract: "regex"
      extraction_regex: ".*So the answer is (.*).\n?"
      prompt_file_path: "cot/svamp/prompt.txt"
      max_tokens: 256
  metrics:
    - "exact_match"
