---
  dataset: "hotpot_qa"
  dataset_split: "validation"
  dataset_subset_name: "fullwiki"
  max_test_samples: 3
  method:
    method_name: "cot"
    method_args:
      client_name: "openai"
      transform: "cot"
      extract: "regex"
      extraction_regex: "(?i).*So the answer is (.*).\n?"
      prompt_file_path: "cot/hotpot_qa/prompt.txt"
      max_tokens: 256
      temperature: 0
      engine: code-davinci-002
      stop_sequence: "\n"
  metrics:
    - "squad"
