---
  dataset:
    dataset_name: "aqua"
    dataset_split: "validation"
    dataset_subset_name: null
    dataset_key_map:
      question: "question"
      choices: "choices"
      answer: "answer"
      id: "id"
  method:
    method_name: "cot"
    method_config_file_path: null
    method_args:
      client_name: "openai"
      transform: "cot.aqua.transform_cot_aqua.CoTAQuATransform"
      extract: "cot.aqua.extract_cot_aqua.CoTAQuAExtract"
      extraction_regex: ".*The answer is (.*).\n?"
      prompt_file_path: "cot/aqua/prompt.txt"
      max_tokens: 512
      temperature: 0
      engine: code-davinci-002
      stop_sequence: "\n\n"
  metrics:
    - "exact_match"
