---
  dataset:
    dataset_name: "commonsense_qa"
    dataset_split: "validation"
    dataset_subset_name: null
    dataset_key_map:
      question: "question"
      choices: "choices"
      answer: "answerKey"
      id: "id"
  method:
    method_name: "cot"
    method_config_file_path: null
    method_args:
      client_name: "openai"
      transform: "cot-commonsense_qa"
      extract: "cot-commonsense_qa"
      extraction_regex: ".*So the answer is (.*).\n?"
      prompt_file_path: "cot/commonsense_qa/prompt.txt"
      max_tokens: 256
      temperature: 0
      engine: code-davinci-002
      stop_sequence: "\n\n"
  metrics:
    - "exact_match"
