---
  dataset:
    dataset_name: "glue"
    dataset_split: "validation"
    dataset_subset_name: "rte"
    dataset_key_map:
      premise: "sentence1"
      hypothesis: "sentence2"
      answer: "label"
      id: "idx"
  method:
    method_name: "cot"
    method_config_file_path: null
    method_args:
      client_name: "openai"
      transform: "cot.rte.transform_cot_rte.CoTRTETransform"
      extract: "cot.rte.extract_cot_rte.CoTRTEExtract"
      extraction_regex: ".*So the answer is (.*).\n?"
      prompt_file_path: "cot/rte/prompt-12shot.txt"
      max_tokens: 512
      temperature: 0
      engine: code-davinci-002
      stop_sequence: "\n\n"
  metrics:
    - "exact_match"
